title: USC/ISI's Datafirst Fault Detection
description: This page will host the datafirst defect detection website. It's still under heavy constructions.
remote_theme: pages-themes/cayman@v0.2.0
github:
  repository_url: https://github.com/usc-isi/faultdetection
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
